# Generated by Django 5.2.17 on 2026-09-24 14:21

import django.core.validators
import django.db.models.deletion
import lounge.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("slug", models.SlugField(max_length=70, unique=True)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("email", models.EmailField(max_length=254)),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("general", "General question"),
                            ("feedback", "Feedback"),
                            ("group", "Group booking or event"),
                            ("other", "Something else"),
                        ],
                        default="general",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "fingerprint",
                    models.CharField(db_index=True, editable=False, max_length=64),
                ),
                ("is_handled", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("source", models.CharField(blank=True, max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "token",
                    models.CharField(
                        default=lounge.models.new_token,
                        editable=False,
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "checkout_key",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                ("customer_name", models.CharField(max_length=80)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("notes", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("preparing", "Being prepared"),
                            ("ready", "Ready for pickup"),
                            ("completed", "Collected"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=12,
                    ),
                ),
                (
                    "staff_note",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="internal note"
                    ),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("item_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "token",
                    models.CharField(
                        default=lounge.models.new_token,
                        editable=False,
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("date", models.DateField(db_index=True)),
                ("time", models.TimeField()),
                (
                    "party_size",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ]
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("declined", "Declined"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "guest_message",
                    models.CharField(
                        blank=True,
                        help_text="Shown on the guest's status page.",
                        max_length=300,
                        verbose_name="message to the guest",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["date", "time"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("slug", models.SlugField(max_length=90, unique=True)),
                ("short_description", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1.00"))
                        ],
                    ),
                ),
                (
                    "illustration",
                    models.CharField(
                        choices=[
                            ("cup-green", "Cup: pale green tea"),
                            ("cup-jasmine", "Cup: jasmine green tea"),
                            ("cup-white", "Cup: white tea"),
                            ("cup-amber", "Cup: amber black tea"),
                            ("cup-dark", "Cup: dark black tea"),
                            ("cup-bergamot", "Cup: black tea with citrus"),
                            ("cup-roasted", "Cup: roasted oolong"),
                            ("cup-chamomile", "Cup: chamomile"),
                            ("cup-mint", "Cup: peppermint"),
                            ("cup-rooibos", "Cup: rooibos"),
                            ("cup-hibiscus", "Cup: hibiscus"),
                            ("mug-chai", "Mug: chai"),
                            ("mug-matcha", "Mug: matcha latte"),
                            ("mug-hojicha", "Mug: hojicha latte"),
                            ("bowl-matcha", "Bowl: matcha"),
                            ("glass-lemon", "Glass: iced lemon tea"),
                            ("glass-green", "Glass: iced green tea"),
                            ("glass-hibiscus", "Glass: iced hibiscus"),
                            ("plate-biscuits", "Plate: biscuits"),
                            ("plate-bun", "Plate: bun"),
                            ("plate-loaf", "Plate: loaf cake"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "caffeine",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "Caffeine-free"),
                            ("low", "Low caffeine"),
                            ("medium", "Medium caffeine"),
                            ("high", "High caffeine"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "brew_temperature_c",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(40),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="brewing temperature (°C)",
                    ),
                ),
                (
                    "brew_time",
                    models.CharField(
                        blank=True,
                        help_text="For example: 2–3 min",
                        max_length=20,
                        verbose_name="steeping time",
                    ),
                ),
                (
                    "tasting_notes",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated, for example: grassy, bright",
                        max_length=120,
                    ),
                ),
                (
                    "allergens",
                    models.CharField(
                        blank=True,
                        help_text="For example: Contains milk",
                        max_length=120,
                    ),
                ),
                (
                    "is_listed",
                    models.BooleanField(default=True, verbose_name="shown on the menu"),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, verbose_name="available to order"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="featured on the home page"
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="lounge.category",
                    ),
                ),
            ],
            options={
                "ordering": ["category__sort_order", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=80)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ]
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="lounge.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="lounge.product",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_listed", "is_available"],
                name="lounge_prod_is_list_7ec3a8_idx",
            ),
        ),
    ]
